apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: LoadBalancer
  selector:
    app: api-gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: api-gateway
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 64Mi
            cpu: "0.25"
          requests:
            memory: 4Mi
            cpu: "0.1"
        ports:
        - containerPort: 3000
        env:
          - name: USER_SERVICE_URL
            valueFrom: 
              configMapKeyRef:
                name: config-map
                key: user-service-url
          - name: USER_SERVICE_PORT
            valueFrom: 
              configMapKeyRef:
                name: config-map
                key: user-service-port
          - name: EMAIL_SERVICE_URL
            valueFrom: 
              configMapKeyRef:
                name: config-map
                key: email-service-url
          - name: EMAIL_SERVICE_PORT
            valueFrom: 
              configMapKeyRef:
                name: config-map
                key: email-service-port
          - name: API_GATEWAY_SERVICE_URL
            valueFrom: 
              configMapKeyRef:
                name: config-map
                key: api-gateway-service-url
          - name: API_GATEWAY_SERVICE_PORT
            valueFrom: 
              configMapKeyRef:
                name: config-map
                key: api-gateway-service-port
