apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: user
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: 32Mi
            cpu: "0.25"
          requests:
            memory: 4Mi
            cpu: "0.1"
        ports:
        - containerPort: 3000
        env:
          - name: USER_SERVICE_URL
            valueFrom: 
              configMapKeyRef:
                name: config-map
                key: user-service-url
          - name: USER_SERVICE_PORT
            valueFrom: 
              configMapKeyRef:
                name: config-map
                key: user-service-port
